name: Java CI with Maven, Docker and SonarCloud in Linux
on:
  push:
  pull_request:
jobs:
  build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4.3
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v4
      with:
        # Shallow clones disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Install Linux GUI Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-0
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build and Test with JaCoCo
      run: xvfb-run mvn verify -Pjacoco
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: SonarCloud Analysis
      if: env.SONAR_TOKEN != ''
      run: >
        mvn sonar:sonar
        -Dsonar.organization=perkashlal
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.projectKey=perkashlal_employee-app
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
