name: Java CI with Maven, Docker and SonarCloud in Linux

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4.3
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

    - name: Install Linux GUI Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-0

    - name: Set Maven Additional Goals
      run: echo "SONARGOAL=sonar:sonar" >> $GITHUB_ENV
      if: ${{ secrets.SONAR_TOKEN }}

    - name: Build with Maven and SonarCloud
      run: >
        xvfb-run mvn verify -Pjacoco $SONARGOAL
        -Dsonar.organization=perkashlal
        -Dsonar.projectKey=perkashlal_employee-app
        -Dsonar.host.url=https://sonarcloud.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
